apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey
  labels:
    app: nginx
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: student-survey
  template:
    metadata:
      labels:
        app: student-survey
    spec:
      containers:
      - name: student-survey
        image: ahmedthrowaway/my-app:latest
        ports:
        - containerPort: 80

