apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQVdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKYkdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNVGMzTWpZdwpNalU1T0RBZUZ3MHlOakF6TURRd05ETTJNemhhRncwek5qQXpNREV3TkRNMk16aGFNRVl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56Y3lOakF5TlRrNE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUIwaEU2WE1NcDllRwpyc3JmUks0d0JsZFJzbXRYVE5sTHBibXU4Z2dKQUNxajQwUTE3NjNuY0hCMklIVFRjcE9UaFdKUFcvZ0VONTBRCitySmVFb1ZDVnFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGTnRoUjQwOWFHa1RDeFppZGlJYVlPY056aVVYTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUUyWApOeklVQ0gxY1lXY3VZNDZvanBUWVZIMkdYVVAxM2QyakhVZExXREp5QWlFQXN0NXVmWE1hMmdtMzF3L1dadmtWClpiMWxxeTdGM0pRZmFGeXN1SUpxcWNzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
    server: https://ec2-52-5-69-117.compute-1.amazonaws.com/k8s/clusters/c-m-kbp652bx
  name: k8cluster
contexts:
- context:
    cluster: k8cluster
    user: k8cluster
  name: k8cluster
current-context: k8cluster
kind: Config
users:
- name: k8cluster
  user:
    token: kubeconfig-user-2wd2j8vd4q:qcv6p6z22fwz72998b2xtqhd77rvlgj6mj4b275mt96tzwcwphsnjb
