apiVersion: v1
kind: Service
metadata:
  name: student-survey-backend-service
spec:
  type: NodePort
  selector:
    app: student-survey-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
