#Ahmed A., SWE645, Spring '26  - Backend Deployment Config File for Assignment 3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-survey-backend
  template:
    metadata:
      labels:
        app: student-survey-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "{{ .Values.backend.databaseUrl }}"
          volumeMounts:
            - name: sqlite-storage
              mountPath: /app/data
      volumes:
        - name: sqlite-storage
          hostPath:
            path: "{{ .Values.backend.sqliteHostPath }}"
            type: DirectoryOrCreate
