#Ahmed A., SWE645, Spring '26  - Front end Deployment Config File for Assignment 3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-survey-frontend
  template:
    metadata:
      labels:
        app: student-survey-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80
